batch_size : 
run_name : "final_test"
epochs : 100
weights_path : 
load_optim_state : 
lr :
mixup-cutmix : 

optimizer : "AdamW"
  weight_decay : 0.1
scheduler : "CosineAnnealingLR"
  T_max : 100, 
  eta_min : 1e-6
    
criterion : "CrossEntropyLoss"
  label_smoothing : 0.1

