# Configuration for ViT-Tiny Training
# model:
#   name: "ViT-Tiny"
#   in_chans : 3
#   embed_dim: 192
#   depth: 12
#   num_heads: 3
#   mlp_ratio: 4.0
#   dropout: 0.15
#   img_size: 224     
#   patch_size: 16 
#   attn_dropout : 0.1    

# training:
#   run_name: "vit-fine-tune"
#   epochs: 100        
#   lr : !!float 3e-04 
#   batch_size: 96   
#   weight_decay: 0.05
#   label_smoothing: 0.1
#   scheduler: "cosine"
#   augmentation: "upresize&randomcrop+RandAugm+mask"
#   weights_path: "checkpoints/vit-pretrain/best.pt"

# dataset:
#   name: "ImageNet-100"
#   num_classes: 100

model : ViT-Tiny

img_size: 224
batch_size: 96

run_name: "Vit-pre-train"
epochs: 100

weights_path: null
load_optim_state: false

mixup_cutmix: false

precision: "fp32"


attn_dropout : 0.0    
dropout: 0.1

early_stopping : null

optimizer:
    name : "AdamW"
    weight_decay: 0.05
    lr : !!float 1e-03

scheduler:
    name : "linear+cosine"
    epochs : 100
    eta_min: 0

criterion:
    name : "CrossEntropyLoss"
    label_smoothing: 0.1


