model : ViT-Tiny

img_size: 224
batch_size: 128
run_name: "vit-run4-mixup-amp"
epochs: 500
weights_path: "checkpoints/vit-fine-tune-mixup-run3/best.pt"
load_optim_state: false
mixup_cutmix: true
precision: "fp16"

attn_dropout : 0.1    
dropout: 0.15

early_stopping :
    patience : 25

optimizer:
    name : "AdamW"
    weight_decay: 0.1
    lr : !!float 1e-4

scheduler:
    name : "ReduceLROnPlateau"
    mode: "max"
    factor: 0.5
    patience: 5
    min_lr: !!float 1e-6


criterion:
    name : "CrossEntropyLoss"
    label_smoothing: 0.0

